### ISSUE TITLE
Getting a NoSuchFieldError on join

### ISSUE THREAD

**Issue by Jcodeerd** [orbyfied/AntiPieRay#3]
```[19:00:46 ERROR]: Could not pass event PlayerJoinEvent to AntiPieRay v1.0.0
java.lang.NoSuchFieldError: b
        at net.orbyfied.antipieray.handler.Injector.inject(Injector.java:39) ~[AntiPieRay-1.0.0.jar:?]
        at net.orbyfied.antipieray.listeners.PlayerListener.onJoin(PlayerListener.java:20) ~[AntiPieRay-1.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[axolotl-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[axolotl-api-1.20.1-R0.1-SNAPSHOT.jar:git-Axolotl-"cb41086"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[axolotl-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[axolotl-1.20.1.jar:git-Axolotl-"cb41086"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[axolotl-1.20.1.jar:git-Axolotl-"cb41086"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[axolotl-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:338) ~[axolotl-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1612) ~[axolotl-1.20.1.jar:git-Axolotl-"cb41086"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:457) ~[axolotl-1.20.1.jar:git-Axolotl-"cb41086"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1419) ~[axolotl-1.20.1.jar:git-Axolotl-"cb41086"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1196) ~[axolotl-1.20.1.jar:git-Axolotl-"cb41086"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[axolotl-1.20.1.jar:git-Axolotl-"cb41086"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by orbyfied** [comment]
probably wrong server version.

i probably shouldve made it clearer that this project is nowhere near a stable/usable state yet, and illl fix these issues and actually make shit work when i have time to work on this again.
